builders:
  realm_generator:
    import: "package:realm_generator/builder.dart"
    builder_factories: ["generateRealmObjects"]
    build_extensions: { ".dart": ["realm_objects.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
