# This file is symlinked into each package's root directory.
include: package:lints/recommended.yaml

analyzer:
  language:
    strict-raw-types: true

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  exclude:
    - lib/**/*.g.dart
    - lib/**/realm_bindings.dart

linter:
  rules:
    avoid_relative_lib_imports: false
    package_api_docs: true
    dangling_library_doc_comments: false

# For more information about the core and recommended set of lints, see
# https://dart.dev/go/core-lints

# For additional information about configuring this file, see
# https://dart.dev/guides/language/analysis-options
