# This file is symlinked into each package's root directory.
include: package:lints/recommended.yaml

analyzer:
  language: 
    strict-casts: true # see https://github.com/dart-lang/language/blob/main/resources/type-system/strict-casts.md
    strict-inference: true  # see https://github.com/dart-lang/language/blob/main/resources/type-system/strict-inference.md
    # strict-raw-types: true # see https://github.com/dart-lang/language/blob/main/resources/type-system/strict-raw-types.md

  plugins:
    - custom_lint

  exclude:
    - lib/**/*.g.dart
    - lib/**/*.realm.dart
    - lib/**/realm_bindings.dart

linter:
  rules:
    avoid_relative_lib_imports: false
    package_api_docs: true

# For more information about the core and recommended set of lints, see
# https://dart.dev/go/core-lints

# For additional information about configuring this file, see
# https://dart.dev/guides/language/analysis-options
