targets:
  $default:
    builders:
      build_cli:
        generate_for:
          - lib/src/cli/metrics/options.dart
      json_serializable:
        generate_for:
          - lib/src/cli/metrics/flutter_info.dart
          - lib/src/cli/metrics/metrics.dart
      realm_generator|realm_object_builder:
        generate_for:
          - test/**.dart
