targets:
  $default:
    builders:
      realm_generator:
        enabled: true
        generate_for:
          include:
            - test/good_test_data/**.dart

builders:
  realm_generator:
    import: "package:realm_generator/realm_generator.dart"
    builder_factories: ["generateRealmObjects"]
    build_extensions: { ".dart": [".realm.dart"] }
    auto_apply: dependents
    build_to: source