name: dev
description: A sample command-line application.
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.3.1

dependencies:
  args: ^2.4.2
  async: ^2.11.0
  cli_launcher: ^0.3.1
  collection: ^1.18.0
  mason_logger: ^0.2.12

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  dev:
