name: ejson_generator_test
description: A separate package for testing the ejson_generator package.
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.0.2

dependencies:
  ejson:
    path: ..

dev_dependencies:
  build_runner: ^2.4.4
  build_test: ^2.1.7
  dart_style: ^2.3.1
  lints: ^2.0.0
  meta: ^1.9.1
  test: ^1.21.0
