targets:
  $default:
    builders:
      build_cli:
        generate_for:
          - lib/src/cli/**/**.dart
      json_serializable:
        generate_for:
          - lib/src/cli/metrics/flutter_info.dart
          - lib/src/cli/metrics/metrics.dart
      realm_generator:
        generate_for:
          include:
            - test/**.dart
            - example/**.dart
      ejson_generator:
        generate_for:
          include:
            - test/**.dart
            - example/**.dart
            
builders:
  realm_generator:
    import: "package:realm_generator/realm_generator.dart"
    builder_factories: ["generateRealmObjects"]
    build_extensions: { ".dart": [".realm.dart"] }
    auto_apply: dependents
    build_to: source
    runs_before: ["ejson_generator|ejson_generator"]
  ejson_generator:
    import: "package:ejson_generator/ejson_generator.dart"
    required_inputs: [".realm.dart"]
    builder_factories: ["getEJsonGenerator"]
    build_extensions: { ".dart": ["ejson.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
