name: realm_ffigen
description: >- 
  A dev package for generating realm bindings.
  Usage: dart run ffigen --config windows.yaml
         dart run ffigen --config macos.yaml
         dart run ffigen --config linux.yaml

documentation: 
publish_to: none

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  realm_dart: ^0.1.0+preview

dev_dependencies:
  pedantic: ^1.9.0
  build_runner: ^1.10.0
  ffigen: ^3.1.0-dev.1