name: realm_ffigen
description: >- 
  A dev package for generating realm bindings.
  Usage: dart run ffigen --config windows.yaml
         dart run ffigen --config macos.yaml
         dart run ffigen --config linux.yaml

publish_to: none

environment:
  sdk: '>=2.15.0 <3.0.0'

dev_dependencies:
  ffigen: ^4.0.0