name: realm_ffigen
description: >- 
  A dev package for generating realm bindings.
  Usage: dart run ffigen --config windows.yaml
         dart run ffigen --config macos.yaml
         dart run ffigen --config linux.yaml

documentation: 
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  realm_dart: 
    path: ../

dev_dependencies:
  lints: ^1.0.1
  build_runner: ^2.1.2
  ffigen: ^4.1.2