// TODO: should be generated by builder
import 'package:ejson/ejson.dart';
import 'package:type_plus/type_plus.dart';

import 'person.dart';

void registerSerializableTypes() {
  TypePlus.add<Person>();
  customDecoders = const {
    Person: decodePerson,
  };
  customEncoders = const {
    Person: encodePerson,
  };
}
