name: ejson_analyzer
description: A starting point for Dart libraries or applications.

version: 0.1.0
repository: https://github.com/realm/realm-dart/ejson/packages/ejson_analyzer

environment:
  sdk: ^3.0.2

dependencies:
  analyzer: ^6.0.0
  ejson_annotation: ^0.1.0
  source_gen: ^1.3.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
