name: Android Build Combine

on:
  workflow_call:

jobs:
  build-android-combined:
    name: Combine Android binaries
    runs-on:  ubuntu-latest
    steps:
      - name: Fetch x86 build
        uses: actions/download-artifact@a327a9c763239d85dc3d78908dbf6ca74acd2e46
        with:
          name: librealm-android-x86
          path: binary/android
      - name: Fetch x86_64 build
        uses: actions/download-artifact@a327a9c763239d85dc3d78908dbf6ca74acd2e46
        with:
          name: librealm-android-x86_64
          path: binary/android
      - name: Fetch armeabi-v7a build
        uses: actions/download-artifact@a327a9c763239d85dc3d78908dbf6ca74acd2e46
        with:
          name: librealm-android-armeabi-v7a
          path: binary/android
      - name: Fetch arm64-v8a build
        uses: actions/download-artifact@a327a9c763239d85dc3d78908dbf6ca74acd2e46
        with:
          name: librealm-android-arm64-v8a
          path: binary/android

      - name: Store combined artifact
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: librealm-android
          path: binary/android
          retention-days: 1

      - name: Delete individual build artifacts
        uses: geekyeggo/delete-artifact@d5464431b27e231287c52139bde3f3c4e32c5622
        with:
          name: |
            librealm-android-x86
            librealm-android-x86_64
            librealm-android-armeabi-v7a
            librealm-android-arm64-v8a