name: Android Build Combine

on:
  workflow_call:

jobs:
  build-android-combined:
    name: Combine Android binaries
    timeout-minutes: 15
    runs-on:  ubuntu-latest
    steps:
      - name: Fetch x86_64 build
        uses: actions/download-artifact@v4
        with:
          name: librealm-android-x86_64
          path: packages/realm_dart/binary/android

      - name: Fetch armeabi-v7a build
        uses: actions/download-artifact@v4
        with:
          name: librealm-android-armeabi-v7a
          path: packages/realm_dart/binary/android

      - name: Fetch arm64-v8a build
        uses: actions/download-artifact@v4
        with:
          name: librealm-android-arm64-v8a
          path: packages/realm_dart/binary/android

      - name: Store combined artifact
        uses: actions/upload-artifact@v4
        with:
          name: librealm-android
          path: packages/realm_dart/binary/android
          retention-days: 1

      - name: Delete individual build artifacts
        uses: geekyeggo/delete-artifact@v4
        with:
          name: |
            librealm-android-x86_64
            librealm-android-armeabi-v7a
            librealm-android-arm64-v8a
          failOnError: false
