# NOTE: This is a common file that is overwritten by realm/ci-actions sync service
# and should only be modified in that repository.

name: Issue Needs Attention
# This workflow is triggered on issue comments.
on:
  issue_comment:
    types: created

jobs:
  applyNeedsAttentionLabel:
    uses: realm/ci-actions/.github/workflows/issue-needs-attention.yml@043cc5a8446748b823957c6ea4d08e6e495ea996
