name: Realm Flutter for MacOS

on:
  push:
    branches:
    # Do not run if change is in these paths
    paths-ignore:
      - 'flutter/**'
      - 'generator/**'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+**' # matches tags like number(s).number(s).number(s)(any) for ex: 1.0.0 and also 1.0.0+beta
  pull_request:
    # Do not run if change is in these paths
    paths-ignore:
        - 'flutter/**'
        - 'generator/**'

jobs:
  CI:
    runs-on: macos-latest
    env:
      REALM_CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build Realm Dart for MacOS
        run: ./scripts/build-macos.sh

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'beta'

      - name: Enable Flutter Desktop support
        run: flutter config --enable-macos-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter drive -d macos --target=test_driver/app.dart --suppress-analytics --dart-entrypoint-args="" #--verbose #-a="Some test name"
        working-directory: ./flutter/realm_flutter/tests
        
