name: realm-flutter

on:
  push:
    branches: [ master ]
    # paths:
    #   - 'flutter/**'
    #   - 'src/**'
    #   - 'lib/**'
  pull_request:
    branches: [ master ]
      # - 'flutter/**'
      # - 'src/**'
      # - 'lib/**'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build for Android x86
        run: |
          mkdir build-android
          cd build-android
          export ANDROID_NDK=$ANDROID_NDK_HOME
          echo ANDROID_NDK: $ANDROID_NDK
          ./../scripts/build-android.sh

      # Uses https://github.com/marketplace/actions/flutter-action
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.x'

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      #- name: Analyze project source
      #  run: dart analyze

     
      - name: Install dependencies
        run: flutter pub get

      - name: Setup Android Emulator cache
        uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-29

      - name: Create Android Emulator and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          arch: x86
          ndk: 21.0.6113669
          cmake: 3.10.2.4988404
          script: echo "Generated Emulator snapshot for caching."


      - name: Run tests on Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
            force-avd-creation: false
            disable-animations: true
            emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
            api-level: 29
            ndk: 21.0.6113669
            arch: x86
            cmake: 3.10.2.4988404
            script: flutter drive --target=test_driver/app.dart
            working-directory: ./flutter/realm_flutter/tests
