name: Terminate BaaS

on:
  workflow_call:
    inputs:
      differentiator:
        description: Differentiator for the BaaS container.
        required: true
        type: string

env:
  REALM_CI: true

jobs:
  terminate-baas:
    runs-on: ubuntu-latest
    name: Terminate BaaS
    timeout-minutes: 15
    defaults:
      run:
        working-directory: packages/realm_dart # TODO: Move out of realm_dart
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Setup Runner
        uses: ./.github/actions/setup-runner

      - name: Terminate baas
        run: dart run realm_dart delete-apps --baasaas-api-key ${{ secrets.BAASAAS_API_KEY }} --differentiator ${{ inputs.differentiator }}
