name: Update samples Realm version
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-samples-version:
    runs-on: ubuntu-latest
    steps:
      - name: 'Get release version'
        id: release-version
        uses: 'WyriHaximus/github-action-get-previous-tag@v1'
        with:
          fallback: 1.0.0

      - name: Run samples update CI
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.REALM_CI_PAT }}" \
          https://github.com/repos/realm/realm-dart-samples/actions/workflows/new_release.yml/dispatches \
          -d '{"ref":"master","inputs":{"version":"{{steps.release-version.outputs.tag}}"}}'