builders:
  ejson:
    import: "package:ejson/generator.dart"
    builder_factories: ["getEJsonGenerator"]
    build_extensions: { ".dart": ["ejson.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
