name: ejson

packages:
  - packages/*

ide:
  intellij: false

command:
  bootstrap:
    hooks:
      post: melos run setup

scripts:
  setup:
    run: >-
      dart pub global activate pana &&
      dart pub global activate coverage

  qa:
    description: Run QA scripts.
    run: >-
      melos run format:check &&
      melos run analyze &&
      melos run test

  qa:full:
    description: Run all QA scripts
    run: >-
      melos run qa &&
      melos run coverage &&
      melos run pana &&
      melos publish --dry-run

  format:
    description: Format Dart code.
    run: dart format .

  format:check:
    description: Check formatting of Dart code.
    run: dart format --output none --set-exit-if-changed .

  analyze:
    description: Analyze Dart code.
    run: dart analyze . --fatal-infos

  test:
    description: Run tests.
    run: dart test -j1 --chain-stack-traces
    exec:
      concurrency: 1
    packageFilters:
      dirExists:
        - test

  coverage:
    description: Run tests with coverage.
    run: dart test --coverage=coverage -j1 --chain-stack-traces
    exec:
      concurrency: 1
    packageFilters:
      dirExists:
        - test      
  
  pana:
    description: Run pana on all packages.
    run: dart pub global run pana --no-warning --exit-code-threshold 40 --source path .
    exec:
      concurrency: 1