name: ejson

packages:
  - packages/*
  - packages/*/example


ide:
  intellij: false

command:
  bootstrap:
    hooks:
      post: melos run setup

scripts:
  setup:
    run: >-
      dart pub global activate coverage &&
      dart pub global activate coverde &&
      dart pub global activate dependency_validator &&
      dart pub global activate pana

  qa:
    description: Run QA scripts.
    run: >-
      melos run format:check &&
      melos run analyze &&
      melos run analyze:deps &&
      melos run test:lints &&
      melos run coverage

  qa:full:
    description: Run all QA scripts (including expensive ones).
    run: >-
      melos run qa &&
      melos run pana &&
      melos publish --dry-run

  format:
    description: Format Dart code.
    run: dart format .

  format:check:
    description: Check formatting of Dart code.
    run: dart format --output none --set-exit-if-changed .

  analyze:
    description: Analyze Dart code.
    run: dart analyze . --fatal-infos
    
  analyze:deps:
    description: Analyze dependencies.
    exec: dart pub global run dependency_validator

  test:
    description: Run tests.
    run: dart test -j1 --chain-stack-traces
    exec:
      concurrency: 1
    packageFilters:
      dirExists:
        - test

  test:lints:
    description: Test that custom lints are working.
    run: melos exec --depends-on=custom_lint -c1 -- dart run custom_lint

  coverage:
    description: Generate, format, and check coverage.
    run: >-
      melos run coverage:generate &&
      melos run coverage:format &&
      melos run coverage:check

  coverage:generate:
    description: Generate coverage.
    run: dart test -j1 --chain-stack-traces --coverage=coverage
    # The following command is not working with coverage:format
    # run: dart pub global run coverage:test_with_coverage --branch-coverage
    exec:
      concurrency: 1
    packageFilters:
      dirExists:
        - test

  coverage:format:
    description: Format coverage.
    run: >-
      dart pub global run coverage:format_coverage
      --in=.
      --report-on=$MELOS_ROOT_PATH
      --lcov --out=lcov.info

  coverage:check:
    description: Check coverage.
    run: dart pub global run coverde check 90 --input=lcov.info
  
  pana:
    description: Run pana on all packages.
    run: dart pub global run pana --no-warning --exit-code-threshold 40 --source path .
    exec:
      concurrency: 1
      packageFilters:
        public: true