name: ejson
description: >-
  EJSON serialization.

  BSON is a binary format used to store JSON-like documents efficiently. 
  EJSON extends JSON defining how all BSON types should be represented in JSON.

topics:
  - ejson
  - bson
  - json
  - build-runner
  - codegen

version: 1.0.0
repository: https://github.com/realm/realm-dart

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.0.1

dependencies:
  analyzer: ^5.2.0
  build: ^2.3.1
  collection: ^1.17.2
  source_gen: ^1.3.2
  type_plus: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
